# Generated by Django 3.0.3 on 2020-03-07 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='testt',
        ),
    ]
