# Generated by Django 3.0.3 on 2020-03-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0002_auto_20200308_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='heloo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='testt',
        ),
    ]
