# Generated by Django 3.0.3 on 2020-03-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0003_auto_20200308_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableTennis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=100)),
                ('venue', models.TextField()),
                ('tour_start_date', models.DateField()),
                ('reg_close_date', models.DateField()),
                ('organiser_name', models.TextField()),
                ('prize', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('total_team', models.IntegerField(blank=True)),
                ('tour_img', models.ImageField(blank=True, upload_to='tableTennis/%Y/%m/%d/')),
            ],
        ),
        migrations.DeleteModel(
            name='heloo',
        ),
    ]
