# Generated by Django 3.0.3 on 2020-03-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0004_auto_20200308_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabletennis',
            name='total_team',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
