# Generated by Django 3.0.3 on 2020-03-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0005_auto_20200308_0428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badminton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=100)),
                ('venue', models.TextField()),
                ('tour_start_date', models.DateField()),
                ('reg_close_date', models.DateField()),
                ('organiser_name', models.TextField()),
                ('prize', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('total_team', models.IntegerField(blank=True, null=True)),
                ('event_img', models.ImageField(blank=True, upload_to='badminton/% Y/% m/% d/')),
            ],
        ),
        migrations.CreateModel(
            name='Chess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=100)),
                ('venue', models.TextField()),
                ('tour_start_date', models.DateField()),
                ('reg_close_date', models.DateField()),
                ('organiser_name', models.TextField()),
                ('prize', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('total_team', models.IntegerField(blank=True, null=True)),
                ('event_img', models.ImageField(blank=True, upload_to='chess/% Y/% m/% d/')),
            ],
        ),
        migrations.CreateModel(
            name='Cricket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=100)),
                ('venue', models.TextField()),
                ('tour_start_date', models.DateField()),
                ('reg_close_date', models.DateField()),
                ('organiser_name', models.TextField()),
                ('prize', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('total_team', models.IntegerField(blank=True, null=True)),
                ('event_img', models.ImageField(blank=True, upload_to='cricket/% Y/% m/% d/')),
            ],
        ),
    ]
