# Generated by Django 3.0.3 on 2020-03-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0007_auto_20200309_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='test/% Y/% m/% d/')),
                ('imgs', models.ImageField(blank=True, upload_to='test')),
            ],
        ),
    ]
