# Generated by Django 3.0.3 on 2020-03-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0008_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(blank=True, upload_to='test/%y/%m/% d/'),
        ),
    ]
