# Generated by Django 3.0.3 on 2020-03-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0009_auto_20200309_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(blank=True, upload_to='test/%Y/%m/%d'),
        ),
    ]
