# Generated by Django 3.0.3 on 2020-03-09 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0011_auto_20200309_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='img',
        ),
    ]
