# Generated by Django 3.0.3 on 2020-03-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0012_remove_img_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='img',
        ),
    ]
