# Generated by Django 3.0.3 on 2020-04-01 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0014_participation_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
