# Generated by Django 3.0.3 on 2020-03-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200308_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='testint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.IntegerField(null=True)),
                ('total_blnull', models.IntegerField(blank=True, null=True)),
                ('total_null', models.IntegerField(null=True)),
                ('totaldef', models.IntegerField(blank=True, default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='destination',
            name='blank1',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='blank2',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='char1',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='char2',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='char3',
        ),
    ]
