# Generated by Django 3.0.3 on 2020-03-07 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20200308_0401'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testint',
        ),
    ]
