# Generated by Django 3.0.3 on 2020-03-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_delete_testint'),
    ]

    operations = [
        migrations.CreateModel(
            name='testint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_nulltrue', models.IntegerField(null=True)),
                ('team_blanktrue', models.IntegerField(blank=True)),
                ('teamblanknull_true', models.IntegerField(blank=True, null=True)),
                ('teamblanktrue_nullfalse', models.IntegerField(blank=True)),
            ],
        ),
    ]
