# Generated by Django 3.0.3 on 2020-03-07 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_testint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testint',
        ),
    ]
